"use strict";
var frutas = ["maçã", "uva"];
frutas.push("banana");
console.log(frutas);
var diaSemana = [];
diaSemana.push("segunda");
diaSemana.push(3);
console.log(diaSemana);
var opções = [];
opções.push("ok");
opções.push(1);
opções.push(true);
console.log(opções);
