"use strict";
var boletim;
boletim = ["ruan", 7];
console.log(boletim);
var notas = [];
notas.push(["ruan", 10]);
notas.push(["rodrigo", 0.5]);
notas.push(["joão", 5]);
console.log(notas);
console.log(notas[0]);
